import WatchDemo from "./WatchDemo";
import AboutQuotes from "./AboutQuotes";
import FooterSocial from "./FooterSocial";

const Check=()=> <span className="check">✓</span>;
const CalendarIcon=()=> <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18"/></svg>;
const UsersIcon=()=> <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>;
const BookingIcon=()=> <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/></svg>;
const GlobeIcon=()=> <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>;
const TeamIcon=()=> <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 11h-6M19 8v6"/></svg>;
const PayIcon=()=> <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20"/></svg>;
const features: [React.ReactNode, string, string, string][] = [
 [<CalendarIcon key="cal"/>,"Smart scheduling","Manage lessons, instructor availability and travel time from one clear calendar, so every day runs smoothly without double bookings.","/smart-scheduling"],
 [<BookingIcon key="book"/>,"Online bookings","Let students book and pay 24/7 from a professional website built around your school, with instant confirmations and reminders.","/online-bookings"],
 [<TeamIcon key="team"/>,"Instructor management","Keep every instructor connected with live calendars, lesson details and earnings, plus shared availability so the whole team stays in sync.","/instructor-hub"],
 [<PayIcon key="pay"/>,"Payments & credits","Accept payments, sell lesson packages and keep every student balance accurate, with card payments, invoices and automatic credit tracking in one place.","/payments-credits"],
 [<UsersIcon key="users"/>,"Student accounts","Give every student a login to book lessons, view packages, track progress and manage their balance.","/student-accounts"],
 [<GlobeIcon key="globe"/>,"Your own website","Launch a trusted, mobile-friendly school website on your own domain, with online booking built in so students can find you and book in one place.","/your-own-website"]];

export default function Home(){return <main>
  <header className="header"><a className="brand" href="#top"><img src="/logo.png" alt="" width={35} height={35}/>DriveInstructor<span>Pro</span></a><nav><a href="#top">Home</a><a href="#features">Features</a><a href="#how">How it works</a><a href="/pricing">Pricing</a><a href="/about">About</a></nav><div className="actions"><a className="button small" href="https://admin.driveinstructor.pro/sign-in">Sign in</a></div></header>
  <section className="hero" id="top"><div className="heroCopy"><div className="eyebrow">Built for modern driving schools</div><h1>Run your driving school on <em>autopilot.</em></h1><p>Bookings, instructors, students, payments and your website, all working together in one simple platform.</p><div className="heroButtons"><a className="button" href="https://admin.driveinstructor.pro/sign-up">Start your free trial →</a><WatchDemo/></div><div className="reassure"><div className="reassureRow"><span><Check/>14 days free</span><span><Check/>No credit card required</span><span><Check/>Cancel anytime</span></div><span><Check/>Set up in minutes</span></div></div>
  <div className="stage" id="demo"><video className="dashShot" src="https://userupload-813333281041-ap-southeast-2-an.s3.ap-southeast-2.amazonaws.com/Videos+/86.mov" autoPlay muted loop playsInline preload="metadata" title="DriveInstructor Pro dashboard showing revenue, bookings and instructor performance"/><div className="float booking"><i>✓</i><span><b>New booking received</b><small>Emma booked a 60 min lesson</small></span><time>Now</time></div><div className="float rating"><i>★★★★★</i><b>Trusted by driving schools</b><small>Simple, reliable and built to grow</small></div></div></section>
  <section className="trust"><p>Everything you need to run a better driving school</p><div><div className="trustRow"><span>✓ Secure payments</span><span>✓ Your own domain</span><span>✓ Cloud hosted</span></div><span>✓ Autopilot</span></div></section>
  <section className="features section" id="features"><div className="heading"><small>ONE CONNECTED PLATFORM</small><h2>Less admin. More time on the road.</h2><p>Replace spreadsheets, paper diaries and disconnected tools with one system built specifically for driving schools.</p></div><div className="grid">{features.map(f=><article key={f[1]} className="featCard"><i>{f[0]}</i><h3>{f[1]}</h3><p>{f[2]}</p><a href={f[3]}>Learn more <span className="featArrow" aria-hidden="true">→</span></a></article>)}</div></section>
  <section className="workflow" id="how"><div><small>A BETTER DAILY WORKFLOW</small><h2>Everything stays in sync, automatically.</h2><p>When a student books, the instructor&apos;s calendar updates, the payment is recorded and confirmations are sent without extra admin.</p><ul><li><Check/><span><b>A single source of truth</b><small>Everyone sees the right booking information in real time.</small></span></li><li><Check/><span><b>Built to prevent clashes</b><small>Global instructor calendars help stop double bookings.</small></span></li><li><Check/><span><b>Professional from day one</b><small>Give students a smooth experience from booking to lesson.</small></span></li></ul><a className="button" href="/pricing">See our pricing →</a></div><div className="flowcard"><header><b>Live booking workflow</b><i><span className="flowLiveDot" aria-hidden="true"/> All systems active</i></header>{[["1","Student books online","Chooses a time, instructor and package","Just now"],["2","Calendar updates","The lesson is reserved instantly","Automatic"],["3","Everyone is notified","Confirmations sent to student and instructor","Delivered"]].map((x,i)=><div key={x[0]} className="flowRow" data-i={i}>{i>0&&<u/>}<article><i>{x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span><em>{x[3]}</em></article></div>)}</div></section>
  <section className="about" id="about"><div className="aboutInner"><div className="aboutCopy"><small>ABOUT US</small><h2>Built with driving schools, for driving schools.</h2><p>We build simple, reliable software so school owners can spend less time on admin and more time helping students become safe, confident drivers.</p><ul><li><Check/><span>Australian-owned and supported</span></li><li><Check/><span>Made for real driving school workflows</span></li><li><Check/><span>Designed to grow with your team</span></li></ul></div><AboutQuotes/></div></section>
  <section className="cta"><div><small>START GROWING TODAY</small><h2>Your whole driving school.<br/>One simple platform.</h2><p>Try every feature free and see how much easier your day can be.</p></div><div><a className="button white" href="https://admin.driveinstructor.pro/sign-up">Start your free trial <span className="btnArrow">→</span></a><small>No credit card required · Cancel anytime</small></div></section>
  <footer><div className="footgrid"><div><a className="brand" href="#top"><img src="/logo.png" alt="" width={35} height={35}/>DriveInstructor<span>Pro</span></a><p>Simple, reliable software that helps driving schools run better and grow with confidence. Bookings, instructors, payments and your website, all in one place.</p></div><div><b>Product</b><a href="#features">Features</a><a href="/pricing">Pricing</a><a href="/instructor-hub">Instructor Hub</a><a href="/your-own-website">School websites</a></div><div><b>Company</b><a href="/about">About us</a><a href="/contact">Contact</a><a href="/help">Help centre</a><a href="#">System status</a></div></div><div className="copyright"><span>© 2026 DriveInstructor Pro. All rights reserved.</span><nav className="legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/security">Security</a></nav><FooterSocial/></div></footer>
</main>}
